/**
 * SEC Filings Index
 * Auto-generated by migrate-sec-filings.ts
 * Last updated: 2026-01-29T17:43:35.805Z
 */

import mstrData from './mstr.json';
import maraData from './mara.json';
import riotData from './riot.json';
import clskData from './clsk.json';
import corzData from './corz.json';
import btdrData from './btdr.json';
import kulrData from './kulr.json';
import xxiData from './xxi.json';
import djtData from './djt.json';
import cepoData from './cepo.json';
import nxttData from './nxtt.json';
import nakaData from './naka.json';
import abtcData from './abtc.json';
import asstData from './asst.json';
import bmnrData from './bmnr.json';
import sbetData from './sbet.json';
import btcsData from './btcs.json';
import btbtData from './btbt.json';
import gameData from './game.json';
import ethmData from './ethm.json';
import fgnxData from './fgnx.json';
import dfdvData from './dfdv.json';
import upxiData from './upxi.json';
import fwdiData from './fwdi.json';
import hsdtData from './hsdt.json';
import stkeData from './stke.json';
import hypdData from './hypd.json';
import purrData from './purr.json';
import naData from './na.json';
import bncData from './bnc.json';
import taoxData from './taox.json';
import twavData from './twav.json';
import cwdData from './cwd.json';
import tronData from './tron.json';
import xrpnData from './xrpn.json';
import cyphData from './cyph.json';
import litsData from './lits.json';
import suigData from './suig.json';
import zoneData from './zone.json';
import tbhData from './tbh.json';
import btogData from './btog.json';
import avxData from './avx.json';

export const SEC_FILINGS: Record<string, any> = {
  'MSTR': mstrData,
  'MARA': maraData,
  'RIOT': riotData,
  'CLSK': clskData,
  'CORZ': corzData,
  'BTDR': btdrData,
  'KULR': kulrData,
  'XXI': xxiData,
  'DJT': djtData,
  'CEPO': cepoData,
  'NXTT': nxttData,
  'NAKA': nakaData,
  'ABTC': abtcData,
  'ASST': asstData,
  'BMNR': bmnrData,
  'SBET': sbetData,
  'BTCS': btcsData,
  'BTBT': btbtData,
  'GAME': gameData,
  'ETHM': ethmData,
  'FGNX': fgnxData,
  'DFDV': dfdvData,
  'UPXI': upxiData,
  'FWDI': fwdiData,
  'HSDT': hsdtData,
  'STKE': stkeData,
  'HYPD': hypdData,
  'PURR': purrData,
  'NA': naData,
  'BNC': bncData,
  'TAOX': taoxData,
  'TWAV': twavData,
  'CWD': cwdData,
  'TRON': tronData,
  'XRPN': xrpnData,
  'CYPH': cyphData,
  'LITS': litsData,
  'SUIG': suigData,
  'ZONE': zoneData,
  'TBH': tbhData,
  'BTOG': btogData,
  'AVX': avxData,
};

export function getCompanyFilings(ticker: string) {
  return SEC_FILINGS[ticker.toUpperCase()];
}

export function getAllFilings() {
  return SEC_FILINGS;
}
